In [ ]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np
import random

In [ ]:
df = pd.read_csv('sentiment_analysis_dataset.csv')

In [ ]:
nltk.download('vader_lexicon')
nltk.download('punkt')

def preprocess_text(text):
    tokens = word_tokenize(text)
    tokens = [t for t in tokens if t.isalpha()]
    return ' '.join(tokens)

df['text'] = df['text'].apply(preprocess_text)


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['sentiment'], test_size=0.2, random_state=42)

In [ ]:
vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
clf = MultinomialNB()
clf.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
y_pred = clf.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.4517374517374517
Classification Report:
              precision    recall  f1-score   support

      joyful       0.67      0.07      0.12        61
         mad       0.65      0.58      0.62       106
    peaceful       0.36      0.94      0.52       135
    powerful       0.63      0.21      0.31        92
         sad       0.71      0.25      0.37        68
      scared       0.56      0.09      0.15        56

    accuracy                           0.45       518
   macro avg       0.60      0.36      0.35       518
weighted avg       0.57      0.45      0.40       518

Confusion Matrix:
[[  4   5  50   2   0   0]
 [  0  62  39   0   4   1]
 [  0   3 127   4   1   0]
 [  2   7  63  19   0   1]
 [  0  10  38   1  17   2]
 [  0   8  37   4   2   5]]


In [ ]:
class ChatBot:
    def __init__(self):
        self.sia = SentimentIntensityAnalyzer()

    def analyze_sentiment(self, text):
        sentiment = self.sia.polarity_scores(text)
        if sentiment['compound'] >= 0.05:
            return "POSITIVE"
        elif sentiment['compound'] <= -0.05:
            return "NEGATIVE"
        else:
            # Corrected indentation
            if abs(sentiment['compound']) < 0.02:  # Use sentiment['compound']
                return "NEUTRAL"
            else:
                return "NEGATIVE" if sentiment['compound'] < 0.0 else "POSITIVE"

    def respond(self, text):
        sentiment = self.analyze_sentiment(text)
        if sentiment == "POSITIVE":
            response = "I'm glad to hear that you're feeling positive!"
        elif sentiment == "NEGATIVE": # Corrected variable name and comparison
            response = "I'm sorry to hear that you're feeling negative. Is there anything I can do to help?"
        else:
            response = "I'm here to chat with you. How can I assist you today?"
        return response, sentiment # Return both response and sentiment

chatbot = ChatBot()
while True:
    user_input = input("You: ")
    response, sentiment = chatbot.respond(user_input)  # Unpack response and sentiment
    print("ChatBot:", response)

    # Verify the sentiment (using stored sentiment)
    if sentiment == "POSITIVE":
        print("Sentiment: POSITIVE ")
    elif sentiment == "NEGATIVE":
        print("Sentiment: NEGATIVE ")
    else:
        print("Sentiment: NEUTRAL ")

You: "I'm so frustrated with this product! 
ChatBot: I'm sorry to hear that you're feeling negative. Is there anything I can do to help?
Sentiment: NEGATIVE 
You: i like this
ChatBot: I'm glad to hear that you're feeling positive!
Sentiment: POSITIVE 
You: its normal
ChatBot: I'm here to chat with you. How can I assist you today?
Sentiment: NEUTRAL 
